version: 2

sources:
  - name: raw
    description: Raw data loaded by Python scripts
    schema: main
    tables:
      - name: raw_nordea_transactions
        description: Raw Nordea bank transactions loaded from CSV exports
        columns:
          - name: transaction_hash
            description: MD5 hash for deduplication (primary key)
          - name: posting_date
            description: Transaction posting date (NULL for pending)
          - name: amount
            description: Transaction amount in DKK (negative for debits)
          - name: sender
            description: Sender account number
          - name: recipient
            description: Recipient account number
          - name: name
            description: Transaction counterparty name
          - name: description
            description: Transaction description/merchant
          - name: balance
            description: Account balance after transaction
          - name: currency
            description: Currency code (DKK)
          - name: reconciled
            description: Reconciliation status
          - name: source_file
            description: Source CSV filename
          - name: loaded_at
            description: Timestamp when record was loaded
